
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-server
    restart: always
    environment:
      # 单机模式
      - MODE=standalone
      # JVM参数
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      # Nacos相关配置
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      # 时区设置
      - TZ=Asia/Shanghai
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-logs:/home/nacos/logs

volumes:
  nacos-data:
  nacos-logs:
